name: website deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: sync
        uses: appleboy/scp-action@main
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.KEY }}
        with:
          source: "_site/*"
          target: "/home/clients/793e7dadbc54f2acdbb0cadc4196e9b5/sites/hcm.ch"
          strip_components: 1