name: website deployment

on:
  push:
    branches: [production]

jobs:
  deploy:
    runs-on: debian-latest
    steps:
      - uses: actions/checkout@production
      - name: sync
        uses: appleboy/scp-action@production
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.KEY }}
        with:
          source: "dest/*"
          target: "/home/clients/793e7dadbc54f2acdbb0cadc4196e9b5/sites/hcm.ch"
          strip_components: 1